[[WebUI]]
arch = "aarch64"
git-tree-sha1 = "e6e6f4d9ee766e4db21a7dccbb67c271dcbc0342"
os = "linux"

	[[WebUI.download]]
	sha256 = "d6c3414199d67f30407e0737bdf33832b7bc7d64121d7af46b6f4c5255ca9840"
	url = "https://github.com/arhik/WebUI_jll/releases/download/v0.1.0/webui.2.5.0-beta.3.aarch64-linux.tar.gz"

[[WebUI]]
arch = "x86_64"
git-tree-sha1 = "53ee91d27fc5568c96191c06e44a9be26cae89a0"
os = "linux"

	[[WebUI.download]]
	sha256 = "37a77bc56387170d26e9863f0ff51d3433ece92e4a9faf35c46135ca13b4006f"
	url = "https://github.com/arhik/WebUI_jll/releases/download/v0.1.0/webui.2.5.0-beta.3.x86_64-linux.tar.gz"

[[WebUI]]
arch = "armv7l"
git-tree-sha1 = "495fef467a9126ddaa2dcf19c04f6ef8dd278afe"
os = "linux"

	[[WebUI.download]]
	sha256 = "ce09f40e53b8d80836f08b2de4b5dfab4df0d1775be4fd48b139a44894760813"
	url = "https://github.com/arhik/WebUI_jll/releases/download/v0.1.0/webui.2.5.0-beta.3.armv7l-linux.tar.gz"

[[WebUI]]
arch = "aarch64"
git-tree-sha1 = "d6f9c97d91c1e35e4232bf58d91a9c5d6ddc7c3a"
os = "macos"

	[[WebUI.download]]
	sha256 = "7f6dd362484d75a1b543a5a5e9178c88aa258300d8e7062c44814510610d960e"
	url = "https://github.com/arhik/WebUI_jll/releases/download/v0.1.0/webui.2.5.0-beta.3.aarch64-macos.tar.gz"

[[WebUI]]
arch = "x86_64"
git-tree-sha1 = "3c18e274ab7d8cadea8a1ec9df2fb1dc4a802d66"
os = "macos"

	[[WebUI.download]]
	sha256 = "32c68d027999885bd9e5f36a2f0002fd3b3a2c846dc5d64833c8b4982aea734c"
	url = "https://github.com/arhik/WebUI_jll/releases/download/v0.1.0/webui.2.5.0-beta.3.x86_64-macos.tar.gz"

[[WebUI]]
arch = "x86_64"
git-tree-sha1 = "ceafb9614dcaa2261cd5e032286b905410587ad8"
os = "windows"

	[[WebUI.download]]
	sha256 = "5035a15b4d799b8c677135f016841d2be33a6931fc28807d9e08c58f4b5c6a38"
	url = "https://github.com/arhik/WebUI_jll/releases/download/v0.1.0/webui.2.5.0-beta.3.x86_64-windows.tar.gz"

