name = "WebUI_jll"
uuid = "f70f86da-aae1-4976-8723-c6a049878ee8"
version = "0.1.0"
authors = ["Arhik <arhik23@gmail.com>"]
description = "Julia package for WebUI 2.5.0-beta.3 library binaries (downloaded at runtime)"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"

[compat]
Dates = "1.11.0"
Downloads = "1.7.0"
SHA = "0.7.0"
Serialization = "1.11.0"
