name = "WebUI_jll"
uuid = "f70f86da-aae1-4976-8723-c6a049878ee8"
version = "2.5.0+0"
authors = ["Arhik <arhik23@gmail.com>"]
description = "Julia package for WebUI library binaries using the artifact system"

[deps]
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"
Inflate = "d25df0c9-e2be-5dd7-82c8-3ad0b3e990b9"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
Inflate = "0.1.5"
Reexport = "1.0"
julia = "1.6.0"
